<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentSystem.Modules.Payments.Application\PaymentSystem.Modules.Payments.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\PaymentSystem.Shared.Presentation\PaymentSystem.Shared.Presentation.csproj" />
  </ItemGroup>

</Project>